# Generated by Django 5.2.17 on 2026-08-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='check_type',
            field=models.CharField(choices=[('NOT_NULL', 'Not Null'), ('UNIQUE', 'Unique'), ('VALID_EMAIL', 'Valid Email'), ('VALID_DATE', 'Valid Date'), ('NUMERIC_VALIDITY', 'Numeric Validity'), ('RANGE', 'Range'), ('SCHEMA', 'Schema'), ('DUPLICATE', 'Duplicate'), ('FRESHNESS', 'Freshness')], max_length=30),
        ),
    ]
