# Generated by Django 5.2.17 on 2026-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dataset_file_format_dataset_file_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CSV", "CSV"),
                    ("JSON", "JSON"),
                    ("EXCEL", "Excel"),
                    ("PARQUET", "Parquet"),
                    ("TSV", "TSV"),
                    ("XML", "XML"),
                    ("DATABASE", "Database"),
                    ("API", "API"),
                    ("S3", "Amazon S3"),
                ],
                max_length=20,
            ),
        ),
    ]
