# Generated by Django 5.2.17 on 2026-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_datasource_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="reliability_grade",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="reliability_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="reliability_status",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
