# Generated by Django 5.2.17 on 2026-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="data_quality_alerts",
            new_name="quality_alerts",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
